spring.application.name=campus-backend
# ??????? (??? campus_db ???????????? Navicat ? MySQL ????????????)
spring.datasource.url=jdbc:mysql://localhost:3306/campus_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=MySQL666
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ?????? (update ??????????????????????????????)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
